# -*- coding: utf-8 -*-
"""BuildDataSetipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cT3cEpsoPMK9R-CfJxV23xaeV6hfPFIw
"""

!pip install -q yfinance

import pandas as pd
import yfinance as yf
from pathlib import Path

STOCKS = ["SPY", "NVDA", "MU", "TSLA"]
MARKET = ["^VIX", "^TNX", "SMH"]
START = "2016-06-20"
END = "2026-06-20"
OUT = Path("dataset")
OUT.mkdir(exist_ok=True)

AGG = {"open": "first", "high": "max", "low": "min",
       "close": "last", "volume": "sum"}

def pull_daily(symbols):
    frames = []
    for s in symbols:
        df = yf.download(s, start=START, end=END,
                         interval="1d", auto_adjust=True,
                         progress=False)
        if df.empty:
            raise RuntimeError("Empty download for " + s)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        cols = ["open", "high", "low", "close", "volume"]
        df = df.rename(columns=str.lower)[cols]
        df.index.name = "timestamp"
        df = df.reset_index()
        df.insert(1, "symbol", s)
        frames.append(df)
        d1 = str(df.timestamp.min().date())
        d2 = str(df.timestamp.max().date())
        print("  " + s + ": " + str(len(df)) + " bars, " + d1 + " to " + d2)
    return pd.concat(frames, ignore_index=True)

def resample(daily, rule):
    out = []
    for s, g in daily.groupby("symbol"):
        g = g.set_index("timestamp").sort_index()
        r = g[list(AGG)].resample(rule).agg(AGG)
        r = r.dropna(subset=["close"]).reset_index()
        r.insert(1, "symbol", s)
        out.append(r)
    return pd.concat(out, ignore_index=True)

def sanity(df, name):
    assert df["close"].gt(0).all(), name + ": bad close"
    dup = df.duplicated(["timestamp", "symbol"]).any()
    assert not dup, name + ": duplicate bars"
    chg = df.sort_values("timestamp").groupby("symbol")["close"].pct_change()
    worst = chg.min()
    assert worst > -0.60, name + ": unadjusted split data, do not use"
    print("  " + name + ": sanity checks passed, " + str(len(df)) + " rows")

print("Pulling daily bars from Yahoo (adjusted)...")
daily = pull_daily(STOCKS + MARKET)
weekly = resample(daily, "W-FRI")
monthly = resample(daily, "ME")

for frame, name in [(daily, "daily"), (weekly, "weekly"), (monthly, "monthly")]:
    sanity(frame, name)
    frame.to_csv(OUT / (name + ".csv"), index=False)
    print("  wrote dataset/" + name + ".csv")

# Long history for the multi horizon section (weekly and monthly need more bars)
START = "1998-01-01"
print("Pulling long history from 1998 (adjusted)...")
daily_long = pull_daily(STOCKS + MARKET)
sanity(daily_long, "daily_long")
daily_long.to_csv(OUT / "daily_long.csv", index=False)
print("  wrote dataset/daily_long.csv")

print("Done")

import shutil
from google.colab import files
shutil.make_archive("PG_dataset", "zip", "dataset")
files.download("PG_dataset.zip")

!pip install -q yfinance

import pandas as pd
import yfinance as yf
from google.colab import files

SYMS = ["SPY", "NVDA", "MU", "TSLA", "SMH", "^VIX"]

frames = []
for s in SYMS:
    df = yf.download(s, period="730d", interval="1h",
                     auto_adjust=True, progress=False)
    if df.empty:
        raise RuntimeError("Empty hourly download for " + s)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    cols = ["open", "high", "low", "close", "volume"]
    df = df.rename(columns=str.lower)[cols]
    df.index = pd.DatetimeIndex(df.index).tz_convert("America/New_York").tz_localize(None)
    df.index.name = "timestamp"
    df = df.reset_index()
    df.insert(1, "symbol", s)
    frames.append(df)
    print("  " + s + ": " + str(len(df)) + " hourly bars, "
          + str(df.timestamp.min()) + " to " + str(df.timestamp.max()))

hourly = pd.concat(frames, ignore_index=True)
hourly.to_csv("hourly.csv", index=False)
print("Total rows: " + str(len(hourly)))
files.download("hourly.csv")

START, END = "1998-01-01", "2026-06-20"
daily_long = pull_daily(STOCKS + MARKET)   # the same function from your dataset cell
daily_long.to_csv("daily_long.csv", index=False)